name: Real-Time Collaboration Tool

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Backend Build
    - name: Install & Build Backend
      run: |
        cd backend
        npm install
        npm run build

    # Frontend Build
    - name: Install & Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    # Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/Real-Time-Collab-Tool

          # Pull latest code
          git pull origin main

          # Backend
          cd backend
          npm install
          npm run build
          pm2 restart collab-backend || pm2 start dist/server.js --name collab-backend

          # Frontend
          cd ../frontend
          npm install
          npm run build
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/

          # Restart nginx
          sudo systemctl restart nginx